services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appendicitis
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn scripts.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app/scripts
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appendicitis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 5s
      retries: 5
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run scripts/streamlit_app/app.py --server.port=8501 --server.address=0.0.0.0 --server.headless true
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./uploads:/app/uploads

    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/appendicitis

volumes:
  postgres_data:
