services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn scripts.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads

    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 5s
      retries: 5
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    command: streamlit run scripts/streamlit_app/frontend.py --server.port=8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./uploads:/app/uploads

    depends_on:
      - api
    environment:
      - API_URL=http://api:8000/predict
