"""Add Peritonitis column

Revision ID: 4a0a1942f978
Revises: 913599a40df3
Create Date: 2025-06-13 16:39:40.822283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0a1942f978'
down_revision: Union[str, None] = '913599a40df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gecmis_hastalar', sa.Column('Peritonitis', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gecmis_hastalar', 'Peritonitis')
    # ### end Alembic commands ###
