"""Create patient and diagnosis tables

Revision ID: 913599a40df3
Revises: 8883cc803692
Create Date: 2025-06-13 16:32:35.374661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913599a40df3'
down_revision: Union[str, None] = '8883cc803692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gecmis_hastalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sex', sa.String(), nullable=False),
    sa.Column('Migratory_Pain', sa.String(), nullable=False),
    sa.Column('Lower_Right_Abd_Pain', sa.String(), nullable=False),
    sa.Column('Contralateral_Rebound_Tenderness', sa.String(), nullable=False),
    sa.Column('Coughing_Pain', sa.String(), nullable=False),
    sa.Column('Nausea', sa.String(), nullable=False),
    sa.Column('Loss_of_Appetite', sa.String(), nullable=False),
    sa.Column('Neutrophilia', sa.String(), nullable=False),
    sa.Column('Ketones_in_Urine', sa.String(), nullable=False),
    sa.Column('RBC_in_Urine', sa.String(), nullable=False),
    sa.Column('WBC_in_Urine', sa.String(), nullable=False),
    sa.Column('Dysuria', sa.String(), nullable=False),
    sa.Column('Stool', sa.String(), nullable=False),
    sa.Column('Psoas_Sign', sa.String(), nullable=False),
    sa.Column('Ipsilateral_Rebound_Tenderness', sa.String(), nullable=False),
    sa.Column('Age', sa.Float(), nullable=False),
    sa.Column('BMI', sa.Float(), nullable=False),
    sa.Column('Height', sa.Float(), nullable=False),
    sa.Column('Weight', sa.Float(), nullable=False),
    sa.Column('Length_of_Stay', sa.Float(), nullable=False),
    sa.Column('Body_Temperature', sa.Float(), nullable=False),
    sa.Column('WBC_Count', sa.Float(), nullable=False),
    sa.Column('Neutrophil_Percentage', sa.Float(), nullable=False),
    sa.Column('RBC_Count', sa.Float(), nullable=False),
    sa.Column('Hemoglobin', sa.Float(), nullable=False),
    sa.Column('RDW', sa.Float(), nullable=False),
    sa.Column('Thrombocyte_Count', sa.Float(), nullable=False),
    sa.Column('CRP', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gecmis_hastalar_id'), 'gecmis_hastalar', ['id'], unique=False)
    op.create_table('gecmis_tanilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('Appendix_Diameter', sa.Float(), nullable=False),
    sa.Column('Appendix_Diameter_Categorized', sa.String(), nullable=False),
    sa.Column('Diagnosis', sa.String(), nullable=False),
    sa.Column('Confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['gecmis_hastalar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gecmis_tanilar_id'), 'gecmis_tanilar', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gecmis_tanilar_id'), table_name='gecmis_tanilar')
    op.drop_table('gecmis_tanilar')
    op.drop_index(op.f('ix_gecmis_hastalar_id'), table_name='gecmis_hastalar')
    op.drop_table('gecmis_hastalar')
    # ### end Alembic commands ###
